name: compilation
on:
  push:
    branches:
      - '*'
      - '!*WIP'
jobs:
  linux-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install libbsd
        run: sudo apt-get install libbsd-dev
      - run: make
