name: norm
on:
  push:
    branches:
      - main
      - '!*WIP'
jobs:
  norminette:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: '.'
